package com.wadpam.pocketvenue.dao;

import com.google.appengine.api.datastore.Key;
import com.wadpam.pocketvenue.domain.Di18nTranslation;

/**
 * Implementation of Business Methods related to entity Di18nTranslation.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-09-30T13:01:41.703+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class Di18nTranslationDaoBean 
	extends GeneratedDi18nTranslationDaoImpl
		implements Di18nTranslationDao 
{

    // Delete all translations for a specific parent
    public int delete(Iterable<Di18nTranslation> di18nIterable) {
        return this.delete(di18nIterable);
    }


}
