package com.wadpam.pocketvenue.dao;

import com.wadpam.pocketvenue.domain.Di18nTranslation;

/**
 * Business Methods interface for entity Di18nTranslation.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-09-30T13:01:41.703+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface Di18nTranslationDao extends GeneratedDi18nTranslationDao {

    /**
     * Delete a list of translations
     * @param di18nIterable the translations to delete
     * @return the number of translations deleted
     */
    public int delete(Iterable<Di18nTranslation> di18nIterable);


}
