package com.wadpam.pocketvenue.dao;

import com.google.appengine.api.datastore.Key;

/**
 * Business Methods interface for entity DTag.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-09-03T08:07:56.959+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DTagDao extends GeneratedDTagDao<Key, Key> {



}
