package com.wadpam.pocketvenue.dao;

/**
 * Implementation of Business Methods related to entity DTag.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-09-03T08:07:56.959+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DTagDaoBean 
	extends GeneratedDTagDaoImpl
		implements DTagDao 
{


}
